language: node_js
node_js:
    - "6.9"
addons:
  postgresql: "9.2"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm test
  - npm run test_pg
  - npm run linter
before_script:
  - psql -c 'create database timesync;' -U postgres
git:
    submodules: false
env:
  - CXX=g++-4.8 TEST_PG_CONNECTION_STRING=postgres://postgres@localhost:5432/timesync SECRET_KEY=secret INSTANCE_NAME=timesync-test
